# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
