# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_batch_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSectionSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('SEMESTER_1', 'SEMESTER 1'), ('SEMESTER_2', 'SEMESTER 2'), ('SEMESTER_3', 'SEMESTER 3'), ('SEMESTER_4', 'SEMESTER 4'), ('SEMESTER_5', 'SEMESTER 5'), ('SEMESTER_6', 'SEMESTER 6'), ('SEMESTER_7', 'SEMESTER 7'), ('SEMESTER_8', 'SEMESTER 8')], default='SEMESTER_1', max_length=10)),
                ('batchSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.BatchSection')),
            ],
        ),
    ]
