# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 10:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20180223_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject')),
            ],
        ),
    ]
