# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 12:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_samplequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplequestion',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000),
        ),
    ]
