from .batch import Batch
from .batchSection import BatchSection
from .batchSectionSemester import BatchSectionSemester
from .examCategory import ExamCategory
from .examInfo import ExamInfo
from .faculty import Faculty
from .facultySubject import FacultySubject
from .sampleQuestion import SampleQuestion
from .subject import Subject
